version: "3.9"

services:
    apache:
        build: "./app/"
        container_name: casfid_prueba_devs_luis_apache
        ports:
            - "8080:80"
        volumes:
            - "./app/src:/var/www/html/"
        links:
            - mysql
    mysql:
        image: mysql:8.0
        container_name: casfid_prueba_devs_luis_mysql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test_db
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3306:3306"
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/dump:/dump"
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: casfid_prueba_devs_luis_pma
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
        links:
            - mysql
        depends_on:
            - mysql